### PR TITLE
Expose xhr.withCredentials with correct default

### LINKED ISSUE #71: Need to define withCredentials
XHR objects are expected to have `xhr.withCredentials == false`.  This is important for feature detection (primarily in code that distinguishes between IE's partial XHR implementations and modern, spec-compliant, implementations.

### PR DESCRIPTION
**Pull request by kumavis**
Fixes #71
Replaces #84

### CODE REVIEW

**Comment by novabyte** [comment]
+1 can we merge this in please.

**Comment by kumavis** [comment]
re-reviewed my code change, and all seems good. this is the correct default behavior for XHRs in the browser. ready to merge.

**Comment by novabyte** [comment]
@kumavis Thanks for re-checking it. I just stumbled across this problem in `jsdom` with a AJAX library I'm using in some headless test cases. The AJAX library detects support for CORS requests with:

```
var cors = 'withCredentials' in tmpxhr;
```

This fails at the moment in jsdom (3.*) because the `withCredentials` property is not on the `XMLHttpRequest` object...

**Comment by novabyte** [comment]
@driverdan Please can you merge this into master and build a new release.

**Comment by kumavis** [comment]
:calling: come on dan drive it home :blue_car:

**Comment by mareksuscak** [comment]
Can we merge this thing @driverdan?

**Comment by mareksuscak** [comment]
@novabyte for working XHR in jsdom you can use my patch https://github.com/mareksuscak/jsdom-xhr-patch until this gets resolved and merged.

**Comment by kumavis** [comment]
HE LIVES :ghost:

**Pull request merged**
